[2025-04-18T09:37:47.009+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-18T09:37:47.316+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_dag.bronze_incremental_load manual__2025-04-18T09:37:38.236464+00:00 [queued]>
[2025-04-18T09:37:47.328+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_dag.bronze_incremental_load manual__2025-04-18T09:37:38.236464+00:00 [queued]>
[2025-04-18T09:37:47.329+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-18T09:37:47.539+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): bronze_incremental_load> on 2025-04-18 09:37:38.236464+00:00
[2025-04-18T09:37:47.545+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'daily_dag', 'bronze_incremental_load', 'manual__2025-04-18T09:37:38.236464+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/daily_dag.py', '--cfg-path', '/tmp/tmpj8z6g23t']
[2025-04-18T09:37:47.547+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask bronze_incremental_load
[2025-04-18T09:37:47.548+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2488) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T09:37:47.549+0000] {standard_task_runner.py:64} INFO - Started process 2489 to run task
[2025-04-18T09:37:47.831+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_dag.bronze_incremental_load manual__2025-04-18T09:37:38.236464+00:00 [running]> on host 4157b7102f42
[2025-04-18T09:37:48.932+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_dag' AIRFLOW_CTX_TASK_ID='bronze_incremental_load' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T09:37:38.236464+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T09:37:38.236464+00:00'
[2025-04-18T09:37:48.933+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-18T09:37:49.189+0000] {base.py:84} INFO - Using connection ID 'spark-conn' for task execution.
[2025-04-18T09:37:49.221+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --packages org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.3.0 --name bronze_incremental_load --deploy-mode client jobs/bronze_incremental_load.py
[2025-04-18T09:37:51.362+0000] {spark_submit.py:645} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.12/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-04-18T09:37:52.175+0000] {spark_submit.py:645} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-04-18T09:37:52.176+0000] {spark_submit.py:645} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-04-18T09:37:52.180+0000] {spark_submit.py:645} INFO - org.apache.iceberg#iceberg-spark-runtime-3.4_2.12 added as a dependency
[2025-04-18T09:37:52.180+0000] {spark_submit.py:645} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-a0c5c0e2-2db5-45e7-b354-ffdc3e9d1ec4;1.0
[2025-04-18T09:37:52.181+0000] {spark_submit.py:645} INFO - confs: [default]
[2025-04-18T09:37:59.975+0000] {spark_submit.py:645} INFO - found org.apache.iceberg#iceberg-spark-runtime-3.4_2.12;1.3.0 in central
[2025-04-18T09:38:00.152+0000] {spark_submit.py:645} INFO - downloading https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.4_2.12/1.3.0/iceberg-spark-runtime-3.4_2.12-1.3.0.jar ...
[2025-04-18T09:38:52.793+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-04-18T09:38:52.793+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-18T09:38:52.795+0000] {process_utils.py:132} INFO - Sending 15 to group 2489. PIDs of all processes in the group: [2490, 2489]
[2025-04-18T09:38:52.837+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2489
[2025-04-18T09:38:52.837+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-18T09:38:52.838+0000] {spark_submit.py:771} INFO - Sending kill signal to spark-submit
[2025-04-18T09:38:52.839+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-18T09:38:52.845+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 555, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 604, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-04-18T09:38:52.966+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_dag, task_id=bronze_incremental_load, run_id=manual__2025-04-18T09:37:38.236464+00:00, execution_date=20250418T093738, start_date=20250418T093747, end_date=20250418T093852
[2025-04-18T09:38:54.533+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2490, status='terminated', started='09:37:49') (2490) terminated with exit code None
[2025-04-18T09:38:54.534+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2489, status='terminated', exitcode=2, started='09:37:47') (2489) terminated with exit code 2
