[2025-04-18T08:46:14.921+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-18T08:46:14.949+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_submit_demo1.spark_submit_task manual__2025-04-18T08:46:12.368386+00:00 [queued]>
[2025-04-18T08:46:14.959+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_submit_demo1.spark_submit_task manual__2025-04-18T08:46:12.368386+00:00 [queued]>
[2025-04-18T08:46:14.982+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-18T08:46:15.510+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2025-04-18 08:46:12.368386+00:00
[2025-04-18T08:46:15.517+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'spark_submit_demo1', 'spark_submit_task', 'manual__2025-04-18T08:46:12.368386+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpkecp_p89']
[2025-04-18T08:46:15.519+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask spark_submit_task
[2025-04-18T08:46:15.519+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=700) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T08:46:15.520+0000] {standard_task_runner.py:64} INFO - Started process 701 to run task
[2025-04-18T08:46:15.721+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_submit_demo1.spark_submit_task manual__2025-04-18T08:46:12.368386+00:00 [running]> on host 6e4add9d1e42
[2025-04-18T08:46:16.362+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='spark_submit_demo1' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T08:46:12.368386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T08:46:12.368386+00:00'
[2025-04-18T08:46:16.362+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-18T08:46:16.382+0000] {base.py:84} INFO - Using connection ID 'spark-conn' for task execution.
[2025-04-18T08:46:16.383+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name airflow-spark-job --deploy-mode client jobs/test.py
[2025-04-18T08:46:17.707+0000] {spark_submit.py:645} INFO - python3: can't open file '/opt/airflow/jobs/test.py': [Errno 2] No such file or directory
[2025-04-18T08:46:17.717+0000] {spark_submit.py:645} INFO - 25/04/18 08:46:17 INFO ShutdownHookManager: Shutdown hook called
[2025-04-18T08:46:17.719+0000] {spark_submit.py:645} INFO - 25/04/18 08:46:17 INFO ShutdownHookManager: Deleting directory /tmp/spark-897da867-0f6b-46bc-9557-cb342b272f86
[2025-04-18T08:46:17.753+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-18T08:46:17.759+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name airflow-spark-job --deploy-mode client jobs/test.py. Error code is: 2.
[2025-04-18T08:46:17.762+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_submit_demo1, task_id=spark_submit_task, run_id=manual__2025-04-18T08:46:12.368386+00:00, execution_date=20250418T084612, start_date=20250418T084614, end_date=20250418T084617
[2025-04-18T08:46:18.036+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task spark_submit_task (Cannot execute: spark-submit --master spark://spark-master:7077 --name airflow-spark-job --deploy-mode client jobs/test.py. Error code is: 2.; 701)
[2025-04-18T08:46:18.062+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-04-18T08:46:18.074+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T08:46:18.075+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
